### ISSUE TITLE
Student Prompt

### ISSUE THREAD

**Issue by neo1427** [neo1427/LMS#2]
**Student Main Prompt:**
It should ask student like what action do you want to perform:
1. Attend a Quiz
2. See Results
3. Exit

User Input:
Provide an Integer (1, 2, or 3) representing the option selected.

Key Actions:
1: Show all the quizzes assigned to the student but not attended
2: Show student result prompt
3: Quit the program

**Comment by neotulasi** [comment]
I have push tthe code please verify and merge it

**Comment by srijanNeo** [comment]
Create the student ID prompt after asking are you a teacher or student

**Comment by neotulasi** [comment]
i have updated the student id check it
