### ISSUE TITLE
Teacher Prompts

### ISSUE THREAD

**Issue by neo1427** [neo1427/LMS#5]
Display the message as below initially when he navigates to teacher prompt from main prompt
**What action do you want to perform?
1. Create a Quiz
2. See Results
3. Exit**

User Input:
Provide an integer (1, 2, or 3) representing the option selected.

Key Actions:
1: Prompts for quiz creation option.
2: Show the teacher result prompt.
3: Quit the program.

**Comment by srijanNeo** [comment]
Create the teacher id

**Comment by neotulasi** [comment]
i have updated the teacher id check it
