### ISSUE TITLE
Quiz Creation Option

### ISSUE THREAD

**Issue by neo1427** [neo1427/LMS#6]
**SHOULD PROMPT THE FOLLOWING:**
1. Enter a title for the Quiz: (The title should be unique under that teacher's name. If the quiz name already exists, display a prompt to enter a different name.)
2. Enter the date of the Quiz (in DD/MM/YY format): (If the date is already scheduled for another quiz, prompt to choose a different date.)
3. Enter the start time of the quiz (in HH:MM format): (Specify the time when the quiz will begin.)
4. Enter the buffer time of the quiz (in minutes): (Buffer time refers to the time after the start time that can be taken to join the quiz.)
5. Proceed to Question Creation prompt after entering all the details.
**(USE PRIMARY KEY FOR EACH COLUMN IN THE TABLE WHEN CREATED TO AVOID DUPLICATES)**

User Input:
Enter the respective details as prompted.

Key Actions:
- Ensure the uniqueness of the quiz title under the teacher's name.
- Verify that the date selected is available for scheduling the quiz.
- Define the start time of the quiz.
- Set the buffer time for joining the quiz.
- After entering all the details, proceed to the question creation prompt.

**Comment by Projectiamneo24** [comment]
have created console based prompt ,go through it

**Comment by neo1427** [comment]
Good work Bharath

**Comment by neo1427** [comment]
@neotulasi can you add the excel sheet link to use so the code reviewer can use it.

**Comment by neotulasi** [comment]
[QUIZ2.xlsx](https://github.com/neo1427/LMS/files/14730328/QUIZ2.xlsx)
[QUIZ1.xlsx](https://github.com/neo1427/LMS/files/14730329/QUIZ1.xlsx)
